import { TopicData } from '../types';

export const memoryManagementData: Record<string, TopicData> = {
  'main-memory': {
    id: 'main-memory',
    title: 'Introduction to Memory Management',
    overview: 'Memory Management is one of the most critical functions of an Operating System. It is responsible for keeping track of each byte in a computer\'s memory, deciding which processes get memory, when they get it, and how much. The OS manages a hierarchy: CPU registers (fastest, tiny), Cache, RAM (main memory), and secondary storage (disk). Programs must be loaded into RAM before the CPU can execute them.',
    whyItExists: 'Without memory management, processes would overwrite each other\'s data, the OS itself could be corrupted, and only one program could run at a time. Memory management enables safe multiprogramming — multiple processes coexist in RAM simultaneously without interfering with each other.',
    analogy: 'RAM is like a restaurant dining area. The OS is the host who decides which customers (processes) get which tables (memory regions). Without the host, customers would fight over seats, steal each other\'s food, and chaos would ensue.',
    keyPoints: [
      { title: 'Memory Hierarchy', description: 'CPU Registers → Cache → RAM (Main Memory) → Secondary Storage. Speed decreases and capacity increases as you go down the hierarchy. Only RAM content can be directly accessed by the CPU.' },
      { title: 'Logical vs Physical Address', description: 'Logical (virtual) address is generated by the CPU. Physical address is the actual RAM location. The Memory Management Unit (MMU) translates between them at runtime.' },
      { title: 'Address Binding', description: 'Addresses in programs can be bound to physical memory at compile time, load time, or execution time. Execution-time binding provides the most flexibility (used in modern OSes).' },
      { title: 'Base and Limit Registers', description: 'The OS uses a base register (start of process memory) and a limit register (size of region) to protect each process\'s memory space. Any access outside this range causes a trap.' },
      { title: 'Memory Protection', description: 'The OS ensures no process can access another process\'s memory. Hardware support (MMU) makes these checks fast without software overhead.' },
      { title: 'Degree of Multiprogramming', description: 'The more processes fit in RAM simultaneously, the higher the CPU utilization. Memory management directly determines how many processes can be active at once.' },
    ],
    interviewNotes: [
      'What is memory management? The OS function that controls and coordinates the allocation of physical memory to processes.',
      'What is the difference between logical and physical addresses? Logical (virtual) is what the CPU generates; physical is the actual RAM location. The MMU translates.',
      'What is address binding? Mapping from logical addresses to physical addresses — can happen at compile time, load time, or execution time.',
      'What are base and limit registers? Hardware registers that define a process\'s allowed memory region, used for protection.',
      'Why is memory hierarchy important? Different levels offer different speed/cost trade-offs. The OS manages movement between levels to maximize performance.',
      'What is multiprogramming? Running multiple processes in memory simultaneously to maximize CPU utilization.',
      'What is memory protection? Ensuring each process can only access its own allocated memory regions.',
    ],
    quickRevision: [
      'RAM = Main Memory = only storage the CPU can directly access.',
      'Logical address ≠ Physical address. MMU translates.',
      'Base register = start of process region. Limit register = size of region.',
      'Memory protection prevents processes from accessing each other\'s memory.',
      'Higher degree of multiprogramming = better CPU utilization.',
      'Memory hierarchy: Registers > Cache > RAM > Disk.',
      'Address binding can be compile-time, load-time, or execution-time.',
    ],
    quiz: [
      {
        id: 'mm-q1',
        question: 'Which component of the memory hierarchy is directly accessible by the CPU?',
        options: ['Hard Disk', 'RAM (Main Memory)', 'SSD', 'Optical Disc'],
        correctIndex: 1,
        explanation: 'Only RAM (Main Memory) can be directly accessed by the CPU. Secondary storage requires data to be loaded into RAM first.'
      },
      {
        id: 'mm-q2',
        question: 'What is the role of the MMU (Memory Management Unit)?',
        options: [
          'It manages the hard disk storage.',
          'It translates logical addresses to physical addresses.',
          'It schedules which process runs next.',
          'It handles I/O operations.'
        ],
        correctIndex: 1,
        explanation: 'The MMU translates logical (virtual) addresses generated by the CPU into physical addresses in RAM. This translation happens at runtime for every memory access.'
      },
      {
        id: 'mm-q3',
        question: 'What do base and limit registers protect against?',
        options: [
          'Cache misses',
          'CPU scheduling conflicts',
          'A process accessing memory outside its allocated region',
          'Disk I/O errors'
        ],
        correctIndex: 2,
        explanation: 'Base and limit registers define the boundaries of a process\'s memory region. Any access outside (base to base+limit) causes a trap, providing memory protection between processes.'
      },
      {
        id: 'mm-q4',
        question: 'Which type of address binding offers the most flexibility at runtime?',
        options: ['Compile-time binding', 'Link-time binding', 'Load-time binding', 'Execution-time binding'],
        correctIndex: 3,
        explanation: 'Execution-time binding allows the process to be moved in memory even after it starts. Modern OSes use this, enabled by hardware (MMU) support.'
      },
      {
        id: 'mm-q5',
        question: 'What is multiprogramming in the context of memory management?',
        options: [
          'Writing programs in multiple languages',
          'Having multiple CPUs in a system',
          'Loading multiple processes into RAM simultaneously to maximize CPU use',
          'Using multiple monitors for output'
        ],
        correctIndex: 2,
        explanation: 'Multiprogramming means keeping multiple processes in RAM at the same time. When one process waits for I/O, the CPU can run another, maximizing utilization.'
      },
      {
        id: 'mm-q6',
        question: 'What is internal fragmentation?',
        options: [
          'Free memory scattered in small chunks between allocated blocks',
          'Wasted memory inside an allocated partition because the process is smaller than the partition',
          'Memory that the OS uses for its own code',
          'A type of cache miss'
        ],
        correctIndex: 1,
        explanation: 'Internal fragmentation is the wasted space inside a partition when a process does not fill the entire allocated block. Example: 100 KB partition, 70 KB process → 30 KB wasted inside.'
      },
      {
        id: 'mm-q7',
        question: 'What is external fragmentation?',
        options: [
          'Wasted space inside allocated partitions',
          'Fragmentation of data on the hard disk',
          'Enough total free memory exists but it is scattered in non-contiguous chunks so a process cannot be allocated',
          'Memory used by the OS kernel'
        ],
        correctIndex: 2,
        explanation: 'External fragmentation occurs when total free memory is enough to satisfy a request, but the free memory is not contiguous. The scattered holes prevent allocation of a large contiguous block.'
      },
      {
        id: 'mm-q8',
        question: 'Which memory allocation strategy picks the smallest free block that is large enough?',
        options: ['First Fit', 'Worst Fit', 'Best Fit', 'Next Fit'],
        correctIndex: 2,
        explanation: 'Best Fit searches all free blocks and selects the smallest one that can fit the process. This minimizes wasted space inside the allocated block but can create tiny leftover fragments.'
      },
      {
        id: 'mm-q9',
        question: 'What is compaction?',
        options: [
          'Compressing files on disk to save space',
          'Moving all processes to one end of memory to merge scattered free blocks into one large contiguous block',
          'A method of CPU scheduling',
          'Reducing the size of the OS kernel'
        ],
        correctIndex: 1,
        explanation: 'Compaction shuffles memory contents to place all occupied regions together, creating one large contiguous free block. This solves external fragmentation but is expensive (requires moving all processes).'
      },
      {
        id: 'mm-q10',
        question: 'What is swapping in memory management?',
        options: [
          'Exchanging CPU cores between processes',
          'Moving a process temporarily from RAM to disk (swap space) to free up memory',
          'Switching between Fixed and Dynamic partitioning',
          'Changing the OS kernel at runtime'
        ],
        correctIndex: 1,
        explanation: 'Swapping moves a process out of RAM to disk (swap-out) when memory is scarce, and brings it back (swap-in) when it needs to run again. It allows more processes than physically fit in RAM.'
      },
      {
        id: 'mm-q11',
        question: 'Which partitioning method can suffer from internal fragmentation but NOT external fragmentation?',
        options: ['Dynamic Partitioning', 'Paging', 'Fixed Partitioning', 'Segmentation'],
        correctIndex: 2,
        explanation: 'Fixed partitioning divides memory into fixed-size blocks. A process gets a block, and if it\'s smaller than the block, internal fragmentation occurs. Since blocks are fixed, there is no external fragmentation.'
      },
      {
        id: 'mm-q12',
        question: 'Which allocation strategy picks the largest free block available?',
        options: ['Best Fit', 'First Fit', 'Next Fit', 'Worst Fit'],
        correctIndex: 3,
        explanation: 'Worst Fit allocates the largest available block. The idea is to leave the largest possible leftover fragment, which is more useful for future allocations than tiny fragments.'
      },
      {
        id: 'mm-q13',
        question: 'Dynamic partitioning avoids which type of fragmentation?',
        options: ['External fragmentation', 'Internal fragmentation', 'Both types', 'Neither type'],
        correctIndex: 1,
        explanation: 'Dynamic partitioning creates partitions exactly the size of each process, so there is no wasted space inside (no internal fragmentation). However, after processes terminate, scattered holes cause external fragmentation.'
      },
      {
        id: 'mm-q14',
        question: 'First Fit allocation strategy allocates memory in which way?',
        options: [
          'Searches all blocks and picks the smallest sufficient one',
          'Allocates the first free block from the beginning that is large enough',
          'Allocates the largest available block',
          'Allocates based on process priority'
        ],
        correctIndex: 1,
        explanation: 'First Fit scans from the start of memory and allocates the very first free block large enough to hold the process. It is fast because it stops searching once a suitable block is found.'
      },
      {
        id: 'mm-q15',
        question: 'What is the main overhead/disadvantage of compaction?',
        options: [
          'It increases internal fragmentation',
          'It reduces the number of processes that can run',
          'It requires moving all active processes in memory, which is very time-consuming',
          'It permanently deletes some processes'
        ],
        correctIndex: 2,
        explanation: 'Compaction requires physically relocating processes in memory, which involves copying large amounts of data and updating all address references. This is a very expensive operation and is only done when necessary.'
      },
    ]
  },

  'memory-layout': {
    id: 'memory-layout',
    title: 'Memory Layout & Process Loading',
    overview: 'When the OS boots, it occupies the lowest memory region. The rest of RAM is divided into user space where processes reside. Each process in memory has a structured layout: Text segment (code), Data segment (global variables), Heap (dynamic allocation, grows upward), Stack (function calls, grows downward). Multiple processes coexist in RAM simultaneously, with the OS tracking each one\'s location.',
    whyItExists: 'A structured memory layout prevents processes from corrupting each other\'s code or data. Separating code, data, heap, and stack enables efficient management of each region and allows the OS to provide protection at segment boundaries.',
    analogy: 'Think of RAM as an apartment building. The ground floor is the building management office (OS). Upper floors are apartments (processes). Each apartment has fixed zones: living room (code), bedroom (data), kitchen (heap), bathroom (stack). Everyone stays in their own apartment.',
    keyPoints: [
      { title: 'OS Region', description: 'The Operating System occupies the lower addresses in memory (or sometimes high addresses depending on architecture). This region is protected from user processes.' },
      { title: 'Text Segment', description: 'Contains the compiled machine code of the program. Usually read-only to prevent accidental modification of instructions.' },
      { title: 'Data Segment', description: 'Contains initialized global and static variables. This region is readable and writable.' },
      { title: 'Heap', description: 'Dynamically allocated memory (malloc/new). Grows upward (toward higher addresses) as the program requests more memory at runtime.' },
      { title: 'Stack', description: 'Stores function call frames, local variables, and return addresses. Grows downward (toward lower addresses). Stack overflow occurs when it meets the heap.' },
      { title: 'Memory Map', description: 'The OS maintains a memory map tracking which regions are allocated to which processes, which are free, and which are reserved for OS use.' },
    ],
    interviewNotes: [
      'Draw and explain the memory layout of a process. Answer: OS → Text → Data → Heap (↑) ... Stack (↓)',
      'What is the difference between heap and stack? Stack is automatic (function frames), heap is manual/dynamic (malloc/new). Stack grows down, heap grows up.',
      'What happens when heap meets stack? Stack overflow (program crash).',
      'Why is the text segment read-only? To prevent a bug or malicious code from modifying program instructions.',
      'What is a memory map? OS data structure tracking which memory regions are used, free, or reserved.',
      'Can two processes share the same physical memory? Only with explicit shared memory mechanisms; otherwise the OS enforces isolation.',
    ],
    quickRevision: [
      'Memory layout (low→high): OS | Text | Data | Heap↑ ... Stack↓',
      'Text = code (read-only). Data = globals. Heap = dynamic (grows up). Stack = function frames (grows down).',
      'OS region is protected from user-space processes.',
      'Stack overflow = heap and stack collide.',
      'OS maintains memory maps to track allocations.',
      'Each process sees its own private memory space (virtual memory).',
    ],
    quiz: []
  },

  'contiguous-allocation': {
    id: 'contiguous-allocation',
    title: 'Contiguous Memory Allocation',
    overview: 'Contiguous memory allocation requires that each process occupies a single contiguous (unbroken) block of RAM. Two main schemes exist: Fixed Partitioning divides memory into equal or unequal fixed-size chunks at system startup. Dynamic Partitioning creates partitions on demand, exactly matching each process\'s size. Both approaches have trade-offs involving fragmentation and complexity.',
    whyItExists: 'Contiguous allocation is the simplest scheme — address translation is trivial (base + offset). Before paging was invented, it was the primary method. Understanding it is essential because modern schemes like paging and segmentation were designed to overcome its limitations.',
    analogy: 'Fixed partitioning is like a parking lot with assigned spaces of fixed size — a motorcycle wastes space in a car-sized spot. Dynamic partitioning is like a flexible parking system that draws lines around each vehicle as it arrives — more efficient but the lot gets fragmented with awkward gaps over time.',
    keyPoints: [
      { title: 'Fixed Partitioning', description: 'Memory is divided into fixed-size partitions at boot time. Simple to implement but causes internal fragmentation (process smaller than partition wastes space). Limits the number and size of processes.' },
      { title: 'Dynamic Partitioning', description: 'Partitions are created exactly the size of each requesting process. No internal fragmentation, but external fragmentation builds up as processes come and go.' },
      { title: 'Internal Fragmentation', description: 'Wasted space inside a partition when the process does not fill it. Only occurs in fixed partitioning. Example: 100 KB partition, 70 KB process → 30 KB wasted.' },
      { title: 'External Fragmentation', description: 'Scattered free blocks that are individually too small for new processes. Total free memory may be sufficient but not contiguous. Occurs in dynamic partitioning.' },
      { title: 'Memory Compaction', description: 'Solution to external fragmentation: move all processes to one end of memory, consolidating free space. Expensive — requires relocating processes and updating addresses.' },
      { title: 'Allocation Strategies', description: 'First Fit (allocate first sufficient block), Best Fit (allocate smallest sufficient block), Worst Fit (allocate largest block). Each has different performance and fragmentation characteristics.' },
    ],
    interviewNotes: [
      'What is fixed partitioning? Memory divided into fixed chunks at boot. Simple but causes internal fragmentation.',
      'What is dynamic partitioning? Partitions created to exactly fit each process. No internal fragmentation but causes external fragmentation.',
      'Which partitioning scheme causes internal fragmentation? Fixed partitioning.',
      'Which partitioning scheme causes external fragmentation? Dynamic partitioning.',
      'How is external fragmentation resolved? Compaction (moving processes) or paging (non-contiguous allocation).',
      'What are the three memory allocation strategies? First Fit, Best Fit, Worst Fit.',
    ],
    quickRevision: [
      'Fixed partitioning → internal fragmentation.',
      'Dynamic partitioning → external fragmentation.',
      'Internal fragmentation = wasted space inside a partition.',
      'External fragmentation = free space scattered in useless holes.',
      'Compaction = merge external fragments (expensive).',
      'First Fit = fast. Best Fit = least waste. Worst Fit = largest leftover.',
    ],
    quiz: []
  },

  'fragmentation': {
    id: 'fragmentation',
    title: 'Fragmentation — Internal & External',
    overview: 'Fragmentation is memory waste that reduces usable memory over time. Internal fragmentation occurs when allocated memory is larger than what the process actually needs — the extra bytes inside the partition are wasted. External fragmentation occurs when free memory is split into many small non-contiguous pieces — individually too small to use, even though the total free space might be sufficient. Both types degrade system performance.',
    whyItExists: 'Fragmentation is an inevitable consequence of allocating and freeing memory over time. Understanding it is crucial because it motivates virtually every advanced memory management technique — paging, segmentation, compaction, and garbage collection all exist to combat fragmentation.',
    analogy: 'Internal fragmentation is like buying a 10-seat van for a 6-person family — 4 seats always empty. External fragmentation is like a parking lot where cars left gaps between them and now a bus cannot park even though total empty space would fit it.',
    keyPoints: [
      { title: 'Internal Fragmentation', description: 'Space wasted inside an allocated block. Occurs in fixed partitioning and paging. Formula: Internal Waste = Partition Size − Process Size.' },
      { title: 'External Fragmentation', description: 'Free memory scattered between allocated blocks. No single free block is big enough for new allocation, even if total free bytes are sufficient.' },
      { title: 'Why Paging Solves External Fragmentation', description: 'Paging breaks processes into fixed-size pages and maps them to physical frames anywhere in memory. No contiguous block needed → external fragmentation eliminated.' },
      { title: 'Why Paging Causes Internal Fragmentation', description: 'A process rarely fills its last page exactly. The remaining bytes in the last page are wasted (internal fragmentation, but limited to at most one page per process).' },
      { title: '50% Rule', description: 'Statistical analysis shows that for N allocated blocks in First Fit, approximately N/2 blocks are lost to fragmentation on average — meaning roughly 1/3 of memory may be unusable.' },
      { title: 'Garbage Collection', description: 'High-level languages (Java, Python) use garbage collectors that automatically reclaim unused heap memory, reducing heap fragmentation without programmer intervention.' },
    ],
    interviewNotes: [
      'Explain the difference between internal and external fragmentation.',
      'Internal = wasted space inside allocated region. External = wasted space between allocated regions.',
      'Which causes more internal fragmentation: large or small page/partition sizes? Large sizes — more likely to have large gaps inside.',
      'How does paging eliminate external fragmentation? By allowing non-contiguous physical allocation — frames can be anywhere in RAM.',
      'Can you have both types of fragmentation simultaneously? Yes — a system with paging has internal fragmentation (last page), and a system with segmentation can have external fragmentation.',
    ],
    quickRevision: [
      'Internal fragmentation = waste inside a block (fixed partitioning / paging).',
      'External fragmentation = waste between blocks (dynamic partitioning).',
      'Internal waste = Partition Size − Process Size.',
      'Paging → no external fragmentation, but small internal fragmentation (last page).',
      '50% rule: ~1/3 of First Fit memory lost to fragmentation.',
      'Compaction solves external. Smaller pages reduce internal.',
    ],
    quiz: []
  },

  'compaction': {
    id: 'compaction',
    title: 'Compaction & Memory Reorganization',
    overview: 'Compaction is a memory management technique that solves external fragmentation by physically relocating all processes to one end of memory, merging all free holes into a single large contiguous block. While effective, compaction is expensive: it requires copying large amounts of data, updating all address pointers, and the system may need to pause processes during the operation.',
    whyItExists: 'External fragmentation causes perfectly usable memory to become unusable. Compaction is the direct solution: merge the scattered free holes into one big usable block. Modern systems often avoid compaction in favor of paging (which eliminates external fragmentation entirely), but compaction is still used in garbage collectors and some embedded systems.',
    analogy: 'Like defragmenting a hard drive — scattered file fragments are moved and consolidated so large contiguous free space is available. Or like pushing all items to one end of a shelf to make room for a large book.',
    keyPoints: [
      { title: 'How Compaction Works', description: 'The OS moves all allocated process blocks to the low end of memory (or one contiguous region), shifting each process\'s physical location. All free blocks merge into one large block at the high end.' },
      { title: 'Relocation Requirement', description: 'For compaction to work, addresses must be relocatable at runtime (execution-time binding). If addresses were bound at compile or load time, processes cannot be moved.' },
      { title: 'Cost of Compaction', description: 'Every byte of every live process must be copied to a new location. On a system with hundreds of megabytes of active data, this is very slow. Processes may need to halt during compaction.' },
      { title: 'When to Compact', description: 'Compaction is triggered when a memory request cannot be satisfied from any single free block, even though total free memory is sufficient. It\'s a last resort before allocation fails.' },
      { title: 'Alternative: Paging', description: 'Paging eliminates external fragmentation by allowing non-contiguous allocation — making compaction unnecessary. Modern OSes use paging instead of compaction.' },
      { title: 'Garbage Collector Compaction', description: 'Java\'s Generational GC and many managed-language runtimes perform compaction (called "copying GC") as part of garbage collection, moving live objects together and reclaiming scattered dead space.' },
    ],
    interviewNotes: [
      'What is compaction? Moving all processes to one end of memory to consolidate free space into one large block.',
      'What is the main disadvantage of compaction? It\'s very expensive — requires copying all live process data and updating all addresses.',
      'When can compaction be performed? Only when execution-time address binding is used (so processes can be relocated).',
      'What is the alternative to compaction for solving external fragmentation? Paging — which eliminates the need for contiguous allocation.',
      'Does compaction solve internal fragmentation? No — it only solves external fragmentation.',
    ],
    quickRevision: [
      'Compaction = move all processes to one end, merge free holes.',
      'Solves external fragmentation only.',
      'Requires execution-time binding (processes must be relocatable).',
      'Very expensive — must copy all live process memory.',
      'Modern alternative: paging (avoids external fragmentation entirely).',
      'Used in GC (copying collectors compact the heap).',
    ],
    quiz: []
  },

  'allocation-strategies': {
    id: 'allocation-strategies',
    title: 'Memory Allocation Strategies',
    overview: 'When a process requests memory, the OS must choose which free block to allocate. Three classic strategies exist: First Fit allocates the first block large enough (fast, low overhead). Best Fit allocates the smallest sufficient block (minimizes internal waste but creates tiny leftover fragments). Worst Fit allocates the largest block (leaves largest possible remainder for future use). Each has different performance, fragmentation, and time complexity characteristics.',
    whyItExists: 'The choice of allocation strategy directly impacts memory utilization, fragmentation levels, and allocation speed. Understanding these strategies helps design better memory allocators and is foundational knowledge for operating systems and systems programming.',
    analogy: 'Imagine free memory blocks as shelves of different sizes, and processes as boxes to place on them. First Fit = grab the first shelf the box fits on. Best Fit = find the shelf where the box fits most snugly. Worst Fit = place it on the biggest shelf so the remaining space is still useful.',
    keyPoints: [
      { title: 'First Fit', description: 'Scan free blocks from the beginning and allocate the first one large enough. Fast (stops early). Tends to leave large free blocks at the end. Can cause accumulation of small fragments at the start of memory.' },
      { title: 'Best Fit', description: 'Search ALL free blocks and pick the smallest sufficient one. Minimizes wasted space in the allocated block but creates many tiny leftover fragments that are useless. Slowest (must scan all blocks).' },
      { title: 'Worst Fit', description: 'Search all free blocks and pick the LARGEST one. Leaves the biggest possible remainder after allocation, which is more likely to be reused. Not always the best performer in practice.' },
      { title: 'Next Fit', description: 'Like First Fit but starts searching from where the last allocation was made (not from the beginning). Distributes small fragments more evenly throughout memory.' },
      { title: 'Performance Comparison', description: 'Simulations show First Fit and Next Fit are generally fastest and produce less fragmentation than Best Fit in practice. Best Fit sounds optimal but often produces worse real-world fragmentation.' },
      { title: 'Modern Allocators', description: 'Real-world allocators (malloc) use combinations of strategies: segregated free lists, slab allocators, and buddy systems — all optimized for specific allocation pattern workloads.' },
    ],
    interviewNotes: [
      'Explain First Fit. Allocates the first free block that is large enough. Fast.',
      'Explain Best Fit. Allocates the smallest sufficient block. Minimizes internal waste but creates tiny fragments.',
      'Explain Worst Fit. Allocates the largest block. Leaves the biggest remainder.',
      'Which strategy is fastest? First Fit (stops at the first match).',
      'Which strategy minimizes wasted space per allocation? Best Fit.',
      'Which strategy performs best in practice? First Fit generally performs best in simulations.',
      'What is Next Fit? Variant of First Fit starting from last allocation point.',
    ],
    quickRevision: [
      'First Fit = first block big enough. Fast. Good overall.',
      'Best Fit = smallest sufficient block. Creates tiny fragments.',
      'Worst Fit = largest block. Leaves large remainder.',
      'Next Fit = First Fit but starts from last allocated position.',
      'Best Fit sounds optimal but often performs worse than First Fit.',
      'Modern allocators: slab allocator, buddy system, segregated lists.',
    ],
    quiz: []
  },

  'swapping': {
    id: 'swapping',
    title: 'Swapping',
    overview: 'Swapping is a memory management technique where the OS temporarily moves a process from RAM to secondary storage (a swap space on disk) to free up memory for other processes. When the swapped process needs to run again, it is brought back into RAM (possibly at a different location). Swapping enables the system to support more active processes than physically fit in RAM at once.',
    whyItExists: 'Systems often have more active processes than can simultaneously fit in RAM. Rather than refusing to run a process or killing it, swapping allows it to be temporarily evicted to disk and resumed later. This is essential for achieving high multiprogramming levels without requiring enormous RAM.',
    analogy: 'Like a student who can only fit a few textbooks on their desk (RAM). When they need a new book, they put one of the current books in their bag (disk) and take the new one out. The books in the bag are still theirs — they can retrieve them anytime.',
    keyPoints: [
      { title: 'Swap Out', description: 'The OS saves the entire process image (memory contents, registers, PCB) to disk and marks its RAM region as free. The process enters a "Suspended" state.' },
      { title: 'Swap In', description: 'When the process is scheduled to run, the OS loads it back from disk into RAM (possibly a different physical location). The process resumes execution.' },
      { title: 'Swap Space', description: 'A dedicated partition or file on disk reserved for swapping. Must be fast (preferably SSD). The OS kernel never swaps itself.' },
      { title: 'Performance Impact', description: 'Swapping is very slow compared to RAM access — disk I/O can be thousands of times slower. Excessive swapping (thrashing) can make a system virtually unusable.' },
      { title: 'Virtual Memory vs Swapping', description: 'Modern systems use virtual memory (paging) which swaps individual pages rather than entire processes. This is more fine-grained and efficient than whole-process swapping.' },
      { title: 'Context for Swap', description: 'The dispatcher must save the full process state before swapping out. On swap-in, the process must be restored to exactly the state it was in before being swapped out.' },
    ],
    interviewNotes: [
      'What is swapping? Moving an entire process from RAM to disk (swap-out) and back (swap-in).',
      'Why is swapping slow? Disk I/O is orders of magnitude slower than RAM access.',
      'What is thrashing? When the system spends more time swapping than executing processes — occurs when processes are swapped in and out too frequently.',
      'What is the difference between swapping and virtual memory/paging? Swapping moves entire processes; paging moves individual pages (more efficient).',
      'Can the OS itself be swapped out? No — the OS kernel always stays in RAM.',
      'What state is a process in while swapped out? Suspended (Blocked Suspended or Ready Suspended).',
    ],
    quickRevision: [
      'Swap out = process moves from RAM → disk.',
      'Swap in = process moves from disk → RAM.',
      'Swap space = reserved disk area for swapped processes.',
      'Swapping is slow (disk I/O vs RAM speed).',
      'Thrashing = too much swapping → system nearly halts.',
      'Modern paging = swaps pages, not whole processes.',
      'OS kernel is never swapped out.',
    ],
    quiz: []
  },
};
